# Generated by Django 4.1.1 on 2022-11-01 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_inn', models.IntegerField()),
                ('client_company_name', models.CharField(max_length=120)),
                ('client_device_number', models.CharField(max_length=60)),
                ('client_modul_number', models.CharField(max_length=60)),
                ('client_number', models.CharField(max_length=40)),
                ('client_single_window_statement', models.FileField(blank=True, null=True, upload_to='media')),
                ('client_statement', models.FileField(blank=True, null=True, upload_to='media')),
                ('description', models.TextField(blank=True, null=True)),
                ('client_statement_added_time', models.DateTimeField(auto_now_add=True)),
                ('user_added_statement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
