# Generated by Django 4.1.1 on 2022-11-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='client_address',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
