# Generated by Django 4.1.1 on 2022-11-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_app', '0002_statements_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='client_single_window_statement',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='statements',
            name='client_statement',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
